spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/postgres
  mvc:
    hiddenmethod:
       filter:
         enabled: true

hashSecret: SECRET

management:
  endpoints:
    web:
      exposure:
        include: '*'