version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "localhost"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
    ports:
      - "35432:5432"
#    volumes:
#      - "./dev-env/postgres/init.sql:/docker-entrypoint-initdb.d/1-init.sql"
