version: "3"
services:
  postgres:
    image: "postgres:13.4-alpine"
    container_name: "localhost"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
    ports:
      - "35432:5432"


  lesson37:
    container_name: "lesson37"
    image: lesson37:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  lesson41:
    container_name: "message-service"
    image: message-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres

