server:
  port: 9091
spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:35432/postgres
  jpa:
    database: POSTGRESQL
    show-sql: false

